builders:
  rivet:
    import: "package:rivet_generator/builder.dart"
    builder_factories: ["rivetBuilder"]
    build_extensions: {".dart": [".rivet.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
