name: inlet_workspace
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

workspace:
  - inlet
  - middlewares/inlet_request_id
  - middlewares/inlet_tracing
  - middlewares/inlet_logger
  - middlewares/inlet_cors
