name: inframe_workspace
publish_to: none

environment:
  sdk: ^3.13.0

workspace:
  - packages/context
  - packages/inlet
  - packages/database/clickhouse
  - packages/database/turso
  - packages/database/rivet
  - packages/database/rivet_generator
  - packages/json_patch
  - packages/chrono_id
  - packages/conflux

dev_dependencies:
  build_runner: ^2.16.1
  postgres: 3.5.12
  rivet: any
  rivet_generator: any
  test: ^1.26.3
  very_good_analysis: ^10.0.0
