name: inframe_workspace
publish_to: none

environment:
  sdk: ^3.13.0

workspace:
  - packages/artificer/providers/artificer_core
  - packages/artificer/providers/artificer_google
  - packages/artificer/providers/artificer_openai
  - packages/context
  - packages/inlet
  - packages/database/clickhouse
  - packages/database/runnel
  - packages/database/turso
  - packages/database/rivet
  - packages/json_patch
  - packages/chrono_id
  - packages/conflux
  - packages/chronicler

dev_dependencies:
  very_good_analysis: ^10.0.0
