name: inframe_workspace
publish_to: none

environment:
  sdk: ^3.13.0

workspace:
  - packages/context
  - packages/inlet
  - packages/database/clickhouse
  - packages/json_patch
  - packages/chrono_id
  - packages/conflux

dev_dependencies:
  very_good_analysis: ^10.0.0
