// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:turso/src/native/turso_bindings_generated.dart')
library;

import 'dart:ffi' as ffi;

/// close the connection preventing any further operations executed over it
/// caller still need to call deinit method to reclaim memory from the
/// instance holding connection SAFETY: caller must guarantee that no ongoing
/// operations are running over connection before calling
/// turso_connection_close(...) method
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<turso_connection_t>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>(symbol: 'turso_connection_close')
external int _turso_connection_close(
  ffi.Pointer<turso_connection_t> self,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_connection_close(
  ffi.Pointer<turso_connection_t> self,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_connection_close(
      self,
      error_opt_out,
    ),
  );
}

/// Deallocate and close a connection SAFETY: caller must ensure that no other
/// code can concurrently or later call methods over deinited connection
@ffi.Native<ffi.Void Function(ffi.Pointer<turso_connection_t>)>()
external void turso_connection_deinit(
  ffi.Pointer<turso_connection_t> self,
);

/// Get autocommit state of the connection
@ffi.Native<ffi.Bool Function(ffi.Pointer<turso_connection_t>)>()
external bool turso_connection_get_autocommit(
  ffi.Pointer<turso_connection_t> self,
);

/// Prepare first statement in a string containing multiple statements in a
/// connection
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<turso_connection_t>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<turso_statement_t>>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>(symbol: 'turso_connection_prepare_first')
external int _turso_connection_prepare_first(
  ffi.Pointer<turso_connection_t> self,
  ffi.Pointer<ffi.Char> sql,
  ffi.Pointer<ffi.Pointer<turso_statement_t>> statement,
  ffi.Pointer<ffi.Size> tail_idx,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_connection_prepare_first(
  ffi.Pointer<turso_connection_t> self,
  ffi.Pointer<ffi.Char> sql,
  ffi.Pointer<ffi.Pointer<turso_statement_t>> statement,
  ffi.Pointer<ffi.Size> tail_idx,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_connection_prepare_first(
      self,
      sql,
      statement,
      tail_idx,
      error_opt_out,
    ),
  );
}

/// Prepare single statement in a connection
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<turso_connection_t>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<turso_statement_t>>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>(symbol: 'turso_connection_prepare_single')
external int _turso_connection_prepare_single(
  ffi.Pointer<turso_connection_t> self,
  ffi.Pointer<ffi.Char> sql,
  ffi.Pointer<ffi.Pointer<turso_statement_t>> statement,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_connection_prepare_single(
  ffi.Pointer<turso_connection_t> self,
  ffi.Pointer<ffi.Char> sql,
  ffi.Pointer<ffi.Pointer<turso_statement_t>> statement,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_connection_prepare_single(
      self,
      sql,
      statement,
      error_opt_out,
    ),
  );
}

/// Connect to the database
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<turso_database_t>,
    ffi.Pointer<ffi.Pointer<turso_connection_t>>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>(symbol: 'turso_database_connect')
external int _turso_database_connect(
  ffi.Pointer<turso_database_t> self,
  ffi.Pointer<ffi.Pointer<turso_connection_t>> connection,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_database_connect(
  ffi.Pointer<turso_database_t> self,
  ffi.Pointer<ffi.Pointer<turso_connection_t>> connection,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_database_connect(
      self,
      connection,
      error_opt_out,
    ),
  );
}

/// Deallocate and close a database SAFETY: caller must ensure that no other
/// code can concurrently or later call methods over deinited database
@ffi.Native<ffi.Void Function(ffi.Pointer<turso_database_t>)>()
external void turso_database_deinit(
  ffi.Pointer<turso_database_t> self,
);

/// Create database holder but do not open it
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<turso_database_config_t>,
    ffi.Pointer<ffi.Pointer<turso_database_t>>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>(symbol: 'turso_database_new')
external int _turso_database_new(
  ffi.Pointer<turso_database_config_t> config,
  ffi.Pointer<ffi.Pointer<turso_database_t>> database,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_database_new(
  ffi.Pointer<turso_database_config_t> config,
  ffi.Pointer<ffi.Pointer<turso_database_t>> database,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_database_new(
      config,
      database,
      error_opt_out,
    ),
  );
}

/// Open database Can return TURSO_IO result if async_io=true is set
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<turso_database_t>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>(symbol: 'turso_database_open')
external int _turso_database_open(
  ffi.Pointer<turso_database_t> database,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_database_open(
  ffi.Pointer<turso_database_t> database,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_database_open(
      database,
      error_opt_out,
    ),
  );
}

/// Setup global database info
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<turso_config_t>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>(symbol: 'turso_setup')
external int _turso_setup(
  ffi.Pointer<turso_config_t> config,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_setup(
  ffi.Pointer<turso_config_t> config,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_setup(
      config,
      error_opt_out,
    ),
  );
}

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<turso_statement_t>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>(symbol: 'turso_statement_bind_positional_blob')
external int _turso_statement_bind_positional_blob(
  ffi.Pointer<turso_statement_t> self,
  int position,
  ffi.Pointer<ffi.Char> ptr,
  int len,
);

turso_status_code_t turso_statement_bind_positional_blob(
  ffi.Pointer<turso_statement_t> self,
  int position,
  ffi.Pointer<ffi.Char> ptr,
  int len,
) {
  return turso_status_code_t.fromValue(
    _turso_statement_bind_positional_blob(
      self,
      position,
      ptr,
      len,
    ),
  );
}

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<turso_statement_t>, ffi.Size, ffi.Double)>(
  symbol: 'turso_statement_bind_positional_double',
)
external int _turso_statement_bind_positional_double(
  ffi.Pointer<turso_statement_t> self,
  int position,
  double value,
);

turso_status_code_t turso_statement_bind_positional_double(
  ffi.Pointer<turso_statement_t> self,
  int position,
  double value,
) {
  return turso_status_code_t.fromValue(
    _turso_statement_bind_positional_double(
      self,
      position,
      value,
    ),
  );
}

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<turso_statement_t>, ffi.Size, ffi.Int64)>(
  symbol: 'turso_statement_bind_positional_int',
)
external int _turso_statement_bind_positional_int(
  ffi.Pointer<turso_statement_t> self,
  int position,
  int value,
);

turso_status_code_t turso_statement_bind_positional_int(
  ffi.Pointer<turso_statement_t> self,
  int position,
  int value,
) {
  return turso_status_code_t.fromValue(
    _turso_statement_bind_positional_int(
      self,
      position,
      value,
    ),
  );
}

/// Bind a positional argument to a statement
@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<turso_statement_t>, ffi.Size)>(
  symbol: 'turso_statement_bind_positional_null',
)
external int _turso_statement_bind_positional_null(
  ffi.Pointer<turso_statement_t> self,
  int position,
);

turso_status_code_t turso_statement_bind_positional_null(
  ffi.Pointer<turso_statement_t> self,
  int position,
) {
  return turso_status_code_t.fromValue(
    _turso_statement_bind_positional_null(
      self,
      position,
    ),
  );
}

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<turso_statement_t>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>(symbol: 'turso_statement_bind_positional_text')
external int _turso_statement_bind_positional_text(
  ffi.Pointer<turso_statement_t> self,
  int position,
  ffi.Pointer<ffi.Char> ptr,
  int len,
);

turso_status_code_t turso_statement_bind_positional_text(
  ffi.Pointer<turso_statement_t> self,
  int position,
  ffi.Pointer<ffi.Char> ptr,
  int len,
) {
  return turso_status_code_t.fromValue(
    _turso_statement_bind_positional_text(
      self,
      position,
      ptr,
      len,
    ),
  );
}

/// Get the array depth of the column at `index`.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<turso_statement_t>, ffi.Size)>()
external int turso_statement_column_array_dimensions(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

/// Get the underlying primitive type name for columns whose declared type is
/// a CREATE TYPE or CREATE DOMAIN.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<turso_statement_t>, ffi.Size)>()
external ffi.Pointer<ffi.Char> turso_statement_column_base_type(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

/// Get column count
@ffi.Native<ffi.Int64 Function(ffi.Pointer<turso_statement_t>)>()
external int turso_statement_column_count(
  ffi.Pointer<turso_statement_t> self,
);

/// Get the declared type name of the column at `index`.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<turso_statement_t>, ffi.Size)>()
external ffi.Pointer<ffi.Char> turso_statement_column_declared_name(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

/// Get the column declared type at the index (e.g. "INTEGER", "TEXT",
/// "DATETIME", etc.) Returns NULL if the column type is not available. C
/// string allocated by Turso must be freed after the usage with corresponding
/// turso_str_deinit(...) method
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<turso_statement_t>, ffi.Size)>()
external ffi.Pointer<ffi.Char> turso_statement_column_decltype(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

/// Classify the column's declared type as builtin / custom / domain / struct
/// / union (see turso_column_kind_t).
@ffi.Native<ffi.Int Function(ffi.Pointer<turso_statement_t>, ffi.Size)>(
  symbol: 'turso_statement_column_kind',
)
external int _turso_statement_column_kind(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

turso_column_kind_t turso_statement_column_kind(
  ffi.Pointer<turso_statement_t> self,
  int index,
) {
  return turso_column_kind_t.fromValue(
    _turso_statement_column_kind(
      self,
      index,
    ),
  );
}

/// Get the column name at the index C string allocated by Turso must be freed
/// after the usage with corresponding turso_str_deinit(...) method
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<turso_statement_t>, ffi.Size)>()
external ffi.Pointer<ffi.Char> turso_statement_column_name(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

/// Deallocate and close a statement SAFETY: caller must ensure that no other
/// code can concurrently or later call methods over deinited statement
@ffi.Native<ffi.Void Function(ffi.Pointer<turso_statement_t>)>()
external void turso_statement_deinit(
  ffi.Pointer<turso_statement_t> self,
);

/// Execute single statement execute returns TURSO_DONE if execution completed
/// execute returns TURSO_IO if async_io was set and execution needs IO in
/// order to make progress
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<turso_statement_t>,
    ffi.Pointer<ffi.Uint64>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>(symbol: 'turso_statement_execute')
external int _turso_statement_execute(
  ffi.Pointer<turso_statement_t> self,
  ffi.Pointer<ffi.Uint64> rows_changes,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_statement_execute(
  ffi.Pointer<turso_statement_t> self,
  ffi.Pointer<ffi.Uint64> rows_changes,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_statement_execute(
      self,
      rows_changes,
      error_opt_out,
    ),
  );
}

/// Finalize a statement finalize returns TURSO_DONE if finalization completed
/// This method must be called in the end of statement execution (either
/// successfull or not)
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<turso_statement_t>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>(symbol: 'turso_statement_finalize')
external int _turso_statement_finalize(
  ffi.Pointer<turso_statement_t> self,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_statement_finalize(
  ffi.Pointer<turso_statement_t> self,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_statement_finalize(
      self,
      error_opt_out,
    ),
  );
}

/// return amount of row modifications (insert/delete operations) made by the
/// most recent executed statement
@ffi.Native<ffi.Int64 Function(ffi.Pointer<turso_statement_t>)>()
external int turso_statement_n_change(
  ffi.Pointer<turso_statement_t> self,
);

/// Return named argument position in a statement Return positive integer with
/// 1-indexed position if named parameter was found Return -1 if parameter was
/// not found
@ffi.Native<ffi.Int64 Function(ffi.Pointer<turso_statement_t>, ffi.Pointer<ffi.Char>)>()
external int turso_statement_named_position(
  ffi.Pointer<turso_statement_t> self,
  ffi.Pointer<ffi.Char> name,
);

/// Return the name of the parameter at 1-based index, including the SQL
/// prefix. Returns NULL for positional-only parameters or out-of-range
/// indices. The caller must free the returned string with turso_str_deinit.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<turso_statement_t>, ffi.Int64)>()
external ffi.Pointer<ffi.Char> turso_statement_parameter_name(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

/// Return parameters count for the statement -1 if pointer is invalid
@ffi.Native<ffi.Int64 Function(ffi.Pointer<turso_statement_t>)>()
external int turso_statement_parameters_count(
  ffi.Pointer<turso_statement_t> self,
);

/// Reset a statement This method must be called in order to cleanup statement
/// resources and prepare it for re-execution Any pending execution will be
/// aborted - be careful and in certain cases ensure that
/// turso_statement_finalize called before turso_statement_reset
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<turso_statement_t>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>(symbol: 'turso_statement_reset')
external int _turso_statement_reset(
  ffi.Pointer<turso_statement_t> self,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_statement_reset(
  ffi.Pointer<turso_statement_t> self,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_statement_reset(
      self,
      error_opt_out,
    ),
  );
}

@ffi.Native<ffi.Int64 Function(ffi.Pointer<turso_statement_t>, ffi.Size)>()
external int turso_statement_row_value_bytes_count(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<turso_statement_t>, ffi.Size)>()
external ffi.Pointer<ffi.Char> turso_statement_row_value_bytes_ptr(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

@ffi.Native<ffi.Double Function(ffi.Pointer<turso_statement_t>, ffi.Size)>()
external double turso_statement_row_value_double(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<turso_statement_t>, ffi.Size)>()
external int turso_statement_row_value_int(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

/// Get the row value at the the index for a current statement state SAFETY:
/// returned pointers will be valid only until next invocation of statement
/// operation (step, finalize, reset, etc) Caller must make sure that any
/// non-owning memory is copied appropriated if it will be used for longer
/// lifetime
@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<turso_statement_t>, ffi.Size)>(
  symbol: 'turso_statement_row_value_kind',
)
external int _turso_statement_row_value_kind(
  ffi.Pointer<turso_statement_t> self,
  int index,
);

turso_type_t turso_statement_row_value_kind(
  ffi.Pointer<turso_statement_t> self,
  int index,
) {
  return turso_type_t.fromValue(
    _turso_statement_row_value_kind(
      self,
      index,
    ),
  );
}

/// Execute one iteration of underlying IO backend after TURSO_IO status code
/// This function either return some ERROR status or TURSO_OK
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<turso_statement_t>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>(symbol: 'turso_statement_run_io')
external int _turso_statement_run_io(
  ffi.Pointer<turso_statement_t> self,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_statement_run_io(
  ffi.Pointer<turso_statement_t> self,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_statement_run_io(
      self,
      error_opt_out,
    ),
  );
}

/// Step statement execution once Returns TURSO_DONE if execution finished
/// Returns TURSO_ROW if execution generated the row (row values can be
/// inspected with corresponding statement methods) Returns TURSO_IO if
/// async_io was set and statement needs to execute IO to make progress
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<turso_statement_t>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>(symbol: 'turso_statement_step')
external int _turso_statement_step(
  ffi.Pointer<turso_statement_t> self,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
);

turso_status_code_t turso_statement_step(
  ffi.Pointer<turso_statement_t> self,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_opt_out,
) {
  return turso_status_code_t.fromValue(
    _turso_statement_step(
      self,
      error_opt_out,
    ),
  );
}

/// Deallocate C string allocated by Turso
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void turso_str_deinit(
  ffi.Pointer<ffi.Char> self,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> turso_version();

final class turso_agg_ctx_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> state;

  static ffi.Pointer<turso_agg_ctx_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> state,
  }) => $allocator<turso_agg_ctx_t>()..ref.state = state;
}

/// Aggregate final callback. The aggregate_context is the value returned by the
/// initializer.
typedef turso_aggregate_final_function_t =
    ffi.Pointer<ffi.NativeFunction<turso_aggregate_final_function_tFunction>>;
typedef turso_aggregate_final_function_tFunction = turso_value_t Function(
  ffi.UintPtr context,
  ffi.Pointer<turso_agg_ctx_t> aggregate_context,
);
typedef Dartturso_aggregate_final_function_tFunction = turso_value_t Function(
  int context,
  ffi.Pointer<turso_agg_ctx_t> aggregate_context,
);

/// Aggregate initializer. Return value is passed unchanged to
/// step/final/destructor callbacks.
typedef turso_aggregate_init_function_t =
    ffi.Pointer<ffi.NativeFunction<turso_aggregate_init_function_tFunction>>;
typedef turso_aggregate_init_function_tFunction = ffi.Pointer<turso_agg_ctx_t> Function(
  ffi.UintPtr context,
);
typedef Dartturso_aggregate_init_function_tFunction = ffi.Pointer<turso_agg_ctx_t> Function(
  int context,
);

/// Aggregate step callback. argv points to argc immutable turso_value_t entries
/// valid only for the call.
typedef turso_aggregate_step_function_t =
    ffi.Pointer<ffi.NativeFunction<turso_aggregate_step_function_tFunction>>;
typedef turso_aggregate_step_function_tFunction = turso_value_t Function(
  ffi.UintPtr context,
  ffi.Pointer<turso_agg_ctx_t> aggregate_context,
  ffi.Int32 argc,
  ffi.Pointer<turso_value_t> argv,
);
typedef Dartturso_aggregate_step_function_tFunction = turso_value_t Function(
  int context,
  ffi.Pointer<turso_agg_ctx_t> aggregate_context,
  int argc,
  ffi.Pointer<turso_value_t> argv,
);

enum turso_codec_location_t {
  TURSO_CODEC_LOCATION_DATABASE(0),
  TURSO_CODEC_LOCATION_WAL(1);

  final int value;
  const turso_codec_location_t(this.value);

  static turso_codec_location_t fromValue(int value) => switch (value) {
    0 => TURSO_CODEC_LOCATION_DATABASE,
    1 => TURSO_CODEC_LOCATION_WAL,
    _ => throw ArgumentError('Unknown value for turso_codec_location_t: $value'),
  };
}

/// Collation callback. Byte ranges are UTF-8 text valid only for the call.
/// Return follows strcmp ordering.
typedef turso_collation_function_t =
    ffi.Pointer<ffi.NativeFunction<turso_collation_function_tFunction>>;
typedef turso_collation_function_tFunction = ffi.Int32 Function(
  ffi.UintPtr context,
  ffi.Pointer<ffi.Uint8> left_ptr,
  ffi.Size left_len,
  ffi.Pointer<ffi.Uint8> right_ptr,
  ffi.Size right_len,
);
typedef Dartturso_collation_function_tFunction = int Function(
  int context,
  ffi.Pointer<ffi.Uint8> left_ptr,
  int left_len,
  ffi.Pointer<ffi.Uint8> right_ptr,
  int right_len,
);

/// Classification of a result column's declared type.
enum turso_column_kind_t {
  TURSO_COLUMN_KIND_NONE(-1),
  TURSO_COLUMN_KIND_BUILTIN(0),
  TURSO_COLUMN_KIND_CUSTOM(1),
  TURSO_COLUMN_KIND_DOMAIN(2),
  TURSO_COLUMN_KIND_STRUCT(3),
  TURSO_COLUMN_KIND_UNION(4);

  final int value;
  const turso_column_kind_t(this.value);

  static turso_column_kind_t fromValue(int value) => switch (value) {
    -1 => TURSO_COLUMN_KIND_NONE,
    0 => TURSO_COLUMN_KIND_BUILTIN,
    1 => TURSO_COLUMN_KIND_CUSTOM,
    2 => TURSO_COLUMN_KIND_DOMAIN,
    3 => TURSO_COLUMN_KIND_STRUCT,
    4 => TURSO_COLUMN_KIND_UNION,
    _ => throw ArgumentError('Unknown value for turso_column_kind_t: $value'),
  };
}

final class turso_config_t extends ffi.Struct {
  /// SAFETY: turso_log_t log argument fields have lifetime scoped to the logger
  /// invocation caller must ensure that data is properly copied if it wants it
  /// to have longer lifetime
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<turso_log_t> log)>> logger;

  external ffi.Pointer<ffi.Char> log_level;

  static ffi.Pointer<turso_config_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<turso_log_t> log)>>
    logger,
    required ffi.Pointer<ffi.Char> log_level,
  }) => $allocator<turso_config_t>()
    ..ref.logger = logger
    ..ref.log_level = log_level;
}

final class turso_connection extends ffi.Opaque {}

/// opaque pointer to the TursoConnection instance SAFETY: the connection must
/// be used exclusive and can't be accessed concurrently
typedef turso_connection_t = turso_connection;

/// Frees per-registration state supplied to scalar, aggregate, or collation
/// callbacks.
typedef turso_context_destructor_t =
    ffi.Pointer<ffi.NativeFunction<turso_context_destructor_tFunction>>;
typedef turso_context_destructor_tFunction = ffi.Void Function(ffi.UintPtr context);
typedef Dartturso_context_destructor_tFunction = void Function(int context);

final class turso_database extends ffi.Opaque {}

/// Database description.
final class turso_database_config_t extends ffi.Struct {
  /// Parameter which defines who drives the IO - callee or the caller (non-zero
  /// parameter value interpreted as async IO)
  @ffi.Uint64()
  external int async_io;

  /// Path to the database file or `:memory:` zero-terminated C string
  external ffi.Pointer<ffi.Char> path;

  /// Optional comma separated list of experimental features to enable
  /// zero-terminated C string or null pointer
  external ffi.Pointer<ffi.Char> experimental_features;

  /// optional VFS parameter explicitly specifying FS backend for the database.
  /// Available options are: - "memory": in-memory backend - "syscall": generic
  /// syscall backend - "io_uring": IO uring (supported only on Linux) -
  /// "experimental_win_iocp": Windows IOCP [experimental](supported only on
  /// Windows)
  external ffi.Pointer<ffi.Char> vfs;

  /// optional encryption cipher as encryption is experimental -
  /// experimental_features must have "encryption" in the list
  external ffi.Pointer<ffi.Char> encryption_cipher;

  /// optional encryption hexkey as encryption is experimental -
  /// experimental_features must have "encryption" in the list
  external ffi.Pointer<ffi.Char> encryption_hexkey;

  /// optional external page codec; callback context must remain valid and
  /// thread-safe until destroy is called
  external ffi.Pointer<turso_page_codec_v1_t> page_codec;

  /// optional bitmask of turso_database_open_flags_t values
  @ffi.Uint32()
  external int open_flags;

  static ffi.Pointer<turso_database_config_t> $allocate(
    ffi.Allocator $allocator, {
    required int async_io,
    required ffi.Pointer<ffi.Char> path,
    required ffi.Pointer<ffi.Char> experimental_features,
    required ffi.Pointer<ffi.Char> vfs,
    required ffi.Pointer<ffi.Char> encryption_cipher,
    required ffi.Pointer<ffi.Char> encryption_hexkey,
    required ffi.Pointer<turso_page_codec_v1_t> page_codec,
    required int open_flags,
  }) => $allocator<turso_database_config_t>()
    ..ref.async_io = async_io
    ..ref.path = path
    ..ref.experimental_features = experimental_features
    ..ref.vfs = vfs
    ..ref.encryption_cipher = encryption_cipher
    ..ref.encryption_hexkey = encryption_hexkey
    ..ref.page_codec = page_codec
    ..ref.open_flags = open_flags;
}

/// opaque pointer to the TursoDatabase instance SAFETY: the database must be
/// opened and closed only once but can be used concurrently
typedef turso_database_t = turso_database;

final class turso_extension_blob_t extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Uint64()
  external int size;

  static ffi.Pointer<turso_extension_blob_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> data,
    required int size,
  }) => $allocator<turso_extension_blob_t>()
    ..ref.data = data
    ..ref.size = size;
}

final class turso_extension_error_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int codeAsInt;

  turso_extension_result_code_t get code => turso_extension_result_code_t.fromValue(codeAsInt);
  set code(turso_extension_result_code_t value) => codeAsInt = value.value;

  external ffi.Pointer<turso_extension_text_t> message;

  static ffi.Pointer<turso_extension_error_t> $allocate(
    ffi.Allocator $allocator, {
    required turso_extension_result_code_t code,
    required ffi.Pointer<turso_extension_text_t> message,
  }) => $allocator<turso_extension_error_t>()
    ..ref.code = code
    ..ref.message = message;
}

enum turso_extension_result_code_t {
  TURSO_EXTENSION_RESULT_OK(0),
  TURSO_EXTENSION_RESULT_ERROR(1),
  TURSO_EXTENSION_RESULT_INVALID_ARGS(2),
  TURSO_EXTENSION_RESULT_UNKNOWN(3),
  TURSO_EXTENSION_RESULT_OOM(4),
  TURSO_EXTENSION_RESULT_CORRUPT(5),
  TURSO_EXTENSION_RESULT_NOT_FOUND(6),
  TURSO_EXTENSION_RESULT_ALREADY_EXISTS(7),
  TURSO_EXTENSION_RESULT_PERMISSION_DENIED(8),
  TURSO_EXTENSION_RESULT_ABORTED(9),
  TURSO_EXTENSION_RESULT_OUT_OF_RANGE(10),
  TURSO_EXTENSION_RESULT_UNIMPLEMENTED(11),
  TURSO_EXTENSION_RESULT_INTERNAL(12),
  TURSO_EXTENSION_RESULT_UNAVAILABLE(13),
  TURSO_EXTENSION_RESULT_CUSTOM_ERROR(14),
  TURSO_EXTENSION_RESULT_EOF(15),
  TURSO_EXTENSION_RESULT_READ_ONLY(16),
  TURSO_EXTENSION_RESULT_ROWID(17),
  TURSO_EXTENSION_RESULT_ROW(18),
  TURSO_EXTENSION_RESULT_INTERRUPT(19),
  TURSO_EXTENSION_RESULT_BUSY(20),
  TURSO_EXTENSION_RESULT_CONSTRAINT_VIOLATION(21);

  final int value;
  const turso_extension_result_code_t(this.value);

  static turso_extension_result_code_t fromValue(int value) => switch (value) {
    0 => TURSO_EXTENSION_RESULT_OK,
    1 => TURSO_EXTENSION_RESULT_ERROR,
    2 => TURSO_EXTENSION_RESULT_INVALID_ARGS,
    3 => TURSO_EXTENSION_RESULT_UNKNOWN,
    4 => TURSO_EXTENSION_RESULT_OOM,
    5 => TURSO_EXTENSION_RESULT_CORRUPT,
    6 => TURSO_EXTENSION_RESULT_NOT_FOUND,
    7 => TURSO_EXTENSION_RESULT_ALREADY_EXISTS,
    8 => TURSO_EXTENSION_RESULT_PERMISSION_DENIED,
    9 => TURSO_EXTENSION_RESULT_ABORTED,
    10 => TURSO_EXTENSION_RESULT_OUT_OF_RANGE,
    11 => TURSO_EXTENSION_RESULT_UNIMPLEMENTED,
    12 => TURSO_EXTENSION_RESULT_INTERNAL,
    13 => TURSO_EXTENSION_RESULT_UNAVAILABLE,
    14 => TURSO_EXTENSION_RESULT_CUSTOM_ERROR,
    15 => TURSO_EXTENSION_RESULT_EOF,
    16 => TURSO_EXTENSION_RESULT_READ_ONLY,
    17 => TURSO_EXTENSION_RESULT_ROWID,
    18 => TURSO_EXTENSION_RESULT_ROW,
    19 => TURSO_EXTENSION_RESULT_INTERRUPT,
    20 => TURSO_EXTENSION_RESULT_BUSY,
    21 => TURSO_EXTENSION_RESULT_CONSTRAINT_VIOLATION,
    _ => throw ArgumentError('Unknown value for turso_extension_result_code_t: $value'),
  };
}

enum turso_extension_text_subtype_t {
  TURSO_EXTENSION_TEXT_TEXT(0),
  TURSO_EXTENSION_TEXT_JSON(1);

  final int value;
  const turso_extension_text_subtype_t(this.value);

  static turso_extension_text_subtype_t fromValue(int value) => switch (value) {
    0 => TURSO_EXTENSION_TEXT_TEXT,
    1 => TURSO_EXTENSION_TEXT_JSON,
    _ => throw ArgumentError('Unknown value for turso_extension_text_subtype_t: $value'),
  };
}

final class turso_extension_text_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int subtypeAsInt;

  turso_extension_text_subtype_t get subtype =>
      turso_extension_text_subtype_t.fromValue(subtypeAsInt);
  set subtype(turso_extension_text_subtype_t value) => subtypeAsInt = value.value;

  external ffi.Pointer<ffi.Uint8> text;

  @ffi.Uint32()
  external int len;

  static ffi.Pointer<turso_extension_text_t> $allocate(
    ffi.Allocator $allocator, {
    required turso_extension_text_subtype_t subtype,
    required ffi.Pointer<ffi.Uint8> text,
    required int len,
  }) => $allocator<turso_extension_text_t>()
    ..ref.subtype = subtype
    ..ref.text = text
    ..ref.len = len;
}

final class turso_extension_value_data_t extends ffi.Union {
  @ffi.Int64()
  external int int_value;

  @ffi.Double()
  external double float_value;

  external ffi.Pointer<turso_extension_text_t> text;

  external ffi.Pointer<turso_extension_blob_t> blob;

  external ffi.Pointer<turso_extension_error_t> error;
}

enum turso_extension_value_type_t {
  TURSO_EXTENSION_VALUE_NULL(0),
  TURSO_EXTENSION_VALUE_INTEGER(1),
  TURSO_EXTENSION_VALUE_FLOAT(2),
  TURSO_EXTENSION_VALUE_TEXT(3),
  TURSO_EXTENSION_VALUE_BLOB(4),
  TURSO_EXTENSION_VALUE_ERROR(5);

  final int value;
  const turso_extension_value_type_t(this.value);

  static turso_extension_value_type_t fromValue(int value) => switch (value) {
    0 => TURSO_EXTENSION_VALUE_NULL,
    1 => TURSO_EXTENSION_VALUE_INTEGER,
    2 => TURSO_EXTENSION_VALUE_FLOAT,
    3 => TURSO_EXTENSION_VALUE_TEXT,
    4 => TURSO_EXTENSION_VALUE_BLOB,
    5 => TURSO_EXTENSION_VALUE_ERROR,
    _ => throw ArgumentError('Unknown value for turso_extension_value_type_t: $value'),
  };
}

final class turso_log_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> message;

  external ffi.Pointer<ffi.Char> target;

  external ffi.Pointer<ffi.Char> file;

  @ffi.Uint64()
  external int timestamp;

  @ffi.Size()
  external int line;

  @ffi.UnsignedInt()
  external int levelAsInt;

  turso_tracing_level_t get level => turso_tracing_level_t.fromValue(levelAsInt);
  set level(turso_tracing_level_t value) => levelAsInt = value.value;

  static ffi.Pointer<turso_log_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> message,
    required ffi.Pointer<ffi.Char> target,
    required ffi.Pointer<ffi.Char> file,
    required int timestamp,
    required int line,
    required turso_tracing_level_t level,
  }) => $allocator<turso_log_t>()
    ..ref.message = message
    ..ref.target = target
    ..ref.file = file
    ..ref.timestamp = timestamp
    ..ref.line = line
    ..ref.level = level;
}

typedef turso_page_codec_destroy_t =
    ffi.Pointer<ffi.NativeFunction<turso_page_codec_destroy_tFunction>>;
typedef turso_page_codec_destroy_tFunction = ffi.Void Function(ffi.Pointer<ffi.Void> ctx);
typedef Dartturso_page_codec_destroy_tFunction = void Function(ffi.Pointer<ffi.Void> ctx);

final class turso_page_codec_header_info_t extends ffi.Struct {
  @ffi.Uint32()
  external int page_size;

  @ffi.Uint8()
  external int reserved_space;

  @ffi.Uint8()
  external int is_supported;

  static ffi.Pointer<turso_page_codec_header_info_t> $allocate(
    ffi.Allocator $allocator, {
    required int page_size,
    required int reserved_space,
    required int is_supported,
  }) => $allocator<turso_page_codec_header_info_t>()
    ..ref.page_size = page_size
    ..ref.reserved_space = reserved_space
    ..ref.is_supported = is_supported;
}

typedef turso_page_codec_probe_header_t =
    ffi.Pointer<ffi.NativeFunction<turso_page_codec_probe_header_tFunction>>;
typedef turso_page_codec_probe_header_tFunction = ffi.Int32 Function(
  ffi.Pointer<ffi.Void> ctx,
  ffi.Pointer<ffi.Uint8> raw_page1_prefix,
  ffi.Size raw_len,
  ffi.Pointer<turso_page_codec_header_info_t> out,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error,
);
typedef Dartturso_page_codec_probe_header_tFunction = int Function(
  ffi.Pointer<ffi.Void> ctx,
  ffi.Pointer<ffi.Uint8> raw_page1_prefix,
  int raw_len,
  ffi.Pointer<turso_page_codec_header_info_t> out,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error,
);
typedef turso_page_codec_transform_t =
    ffi.Pointer<ffi.NativeFunction<turso_page_codec_transform_tFunction>>;
typedef turso_page_codec_transform_tFunction = ffi.Int32 Function(
  ffi.Pointer<ffi.Void> ctx,
  ffi.Uint32 page_no,
  ffi.UnsignedInt location,
  ffi.Pointer<ffi.Uint8> input,
  ffi.Size input_len,
  ffi.Pointer<ffi.Uint8> output,
  ffi.Size output_len,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error,
);
typedef Dartturso_page_codec_transform_tFunction = int Function(
  ffi.Pointer<ffi.Void> ctx,
  int page_no,
  turso_codec_location_t location,
  ffi.Pointer<ffi.Uint8> input,
  int input_len,
  ffi.Pointer<ffi.Uint8> output,
  int output_len,
  ffi.Pointer<ffi.Pointer<ffi.Char>> error,
);

final class turso_page_codec_v1_t extends ffi.Struct {
  @ffi.Uint32()
  external int abi_version;

  external ffi.Pointer<ffi.Void> ctx;

  @ffi.Uint8()
  external int reserved_space;

  /// Stable, non-secret identifier for this codec configuration. Must change
  /// whenever encoded bytes could differ.
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> codec_id;

  external turso_page_codec_destroy_t destroy;

  external turso_page_codec_probe_header_t probe_header;

  external turso_page_codec_transform_t decode_page;

  external turso_page_codec_transform_t encode_page;
}

/// Scalar callback. argv points to argc immutable turso_value_t entries valid
/// only for the call.
typedef turso_scalar_function_t = ffi.Pointer<ffi.NativeFunction<turso_scalar_function_tFunction>>;
typedef turso_scalar_function_tFunction = turso_value_t Function(
  ffi.UintPtr context,
  ffi.Int32 argc,
  ffi.Pointer<turso_value_t> argv,
  turso_context_destructor_t context_destructor,
  turso_value_destructor_t value_destructor,
);
typedef Dartturso_scalar_function_tFunction = turso_value_t Function(
  int context,
  int argc,
  ffi.Pointer<turso_value_t> argv,
  turso_context_destructor_t context_destructor,
  turso_value_destructor_t value_destructor,
);

final class turso_statement extends ffi.Opaque {}

/// opaque pointer to the TursoStatement instance SAFETY: the statement must be
/// used exclusive and can't be accessed concurrently
typedef turso_statement_t = turso_statement;

enum turso_status_code_t {
  TURSO_OK(0),
  TURSO_DONE(1),
  TURSO_ROW(2),
  TURSO_IO(3),
  TURSO_BUSY(4),
  TURSO_INTERRUPT(5),
  TURSO_BUSY_SNAPSHOT(6),
  TURSO_ERROR(127),
  TURSO_MISUSE(128),
  TURSO_CONSTRAINT(129),
  TURSO_READONLY(130),
  TURSO_DATABASE_FULL(131),
  TURSO_NOTADB(132),
  TURSO_CORRUPT(133),
  TURSO_IOERR(134);

  final int value;
  const turso_status_code_t(this.value);

  static turso_status_code_t fromValue(int value) => switch (value) {
    0 => TURSO_OK,
    1 => TURSO_DONE,
    2 => TURSO_ROW,
    3 => TURSO_IO,
    4 => TURSO_BUSY,
    5 => TURSO_INTERRUPT,
    6 => TURSO_BUSY_SNAPSHOT,
    127 => TURSO_ERROR,
    128 => TURSO_MISUSE,
    129 => TURSO_CONSTRAINT,
    130 => TURSO_READONLY,
    131 => TURSO_DATABASE_FULL,
    132 => TURSO_NOTADB,
    133 => TURSO_CORRUPT,
    134 => TURSO_IOERR,
    _ => throw ArgumentError('Unknown value for turso_status_code_t: $value'),
  };
}

enum turso_tracing_level_t {
  TURSO_TRACING_LEVEL_ERROR(1),
  TURSO_TRACING_LEVEL_WARN(2),
  TURSO_TRACING_LEVEL_INFO(3),
  TURSO_TRACING_LEVEL_DEBUG(4),
  TURSO_TRACING_LEVEL_TRACE(5);

  final int value;
  const turso_tracing_level_t(this.value);

  static turso_tracing_level_t fromValue(int value) => switch (value) {
    1 => TURSO_TRACING_LEVEL_ERROR,
    2 => TURSO_TRACING_LEVEL_WARN,
    3 => TURSO_TRACING_LEVEL_INFO,
    4 => TURSO_TRACING_LEVEL_DEBUG,
    5 => TURSO_TRACING_LEVEL_TRACE,
    _ => throw ArgumentError('Unknown value for turso_tracing_level_t: $value'),
  };
}

enum turso_type_t {
  TURSO_TYPE_UNKNOWN(0),
  TURSO_TYPE_INTEGER(1),
  TURSO_TYPE_REAL(2),
  TURSO_TYPE_TEXT(3),
  TURSO_TYPE_BLOB(4),
  TURSO_TYPE_NULL(5);

  final int value;
  const turso_type_t(this.value);

  static turso_type_t fromValue(int value) => switch (value) {
    0 => TURSO_TYPE_UNKNOWN,
    1 => TURSO_TYPE_INTEGER,
    2 => TURSO_TYPE_REAL,
    3 => TURSO_TYPE_TEXT,
    4 => TURSO_TYPE_BLOB,
    5 => TURSO_TYPE_NULL,
    _ => throw ArgumentError('Unknown value for turso_type_t: $value'),
  };
}

/// Frees a value returned by a managed scalar or aggregate callback after Turso
/// copies it.
typedef turso_value_destructor_t =
    ffi.Pointer<ffi.NativeFunction<turso_value_destructor_tFunction>>;
typedef turso_value_destructor_tFunction = ffi.Void Function(ffi.Pointer<turso_value_t> result);
typedef Dartturso_value_destructor_tFunction = void Function(ffi.Pointer<turso_value_t> result);

final class turso_value_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int value_typeAsInt;

  turso_extension_value_type_t get value_type =>
      turso_extension_value_type_t.fromValue(value_typeAsInt);
  set value_type(turso_extension_value_type_t value) => value_typeAsInt = value.value;

  external turso_extension_value_data_t value;
}
