// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format off
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import 'src/embeddings/compatible_embedding_model.dart' as p0;
import 'src/embeddings/embeddings.dart' as p1;
import 'src/errors.dart' as p2;
import 'src/generation/generation.dart' as p3;
import 'src/messages/messages.dart' as p4;
import 'src/models.dart' as p5;
import 'src/native.dart' as p6;
import 'src/observations.dart' as p7;
import 'src/protocols/chat/chat_models.dart' as p8;
import 'src/protocols/responses/responses_models.dart' as p9;
import 'src/protocols/sse.dart' as p10;
import 'src/settings.dart' as p11;
import 'src/tools/tools.dart' as p12;

void initializeMappers() {
  p0.EmbeddingOptionsMapper.ensureInitialized();
  p1.EmbeddingInputMapper.ensureInitialized();
  p1.EmbeddingRequestMapper.ensureInitialized();
  p1.EmbeddingCapabilitiesMapper.ensureInitialized();
  p1.EmbeddingResultMapper.ensureInitialized();
  p1.IndexedEmbeddingMapper.ensureInitialized();
  p1.EmbeddingBatchMapper.ensureInitialized();
  p2.AiErrorMapper.ensureInitialized();
  p2.InvalidRequestErrorMapper.ensureInitialized();
  p2.UnsupportedFeatureErrorMapper.ensureInitialized();
  p2.ProviderErrorMapper.ensureInitialized();
  p2.TransportErrorMapper.ensureInitialized();
  p2.ProtocolErrorMapper.ensureInitialized();
  p2.ResponseLimitErrorMapper.ensureInitialized();
  p2.ClientClosedErrorMapper.ensureInitialized();
  p2.DeliveryStateMapper.ensureInitialized();
  p3.GenerationOptionsMapper.ensureInitialized();
  p3.ResolvedGenerationOptionsMapper.ensureInitialized();
  p3.GenerationRequestMapper.ensureInitialized();
  p3.UsageMapper.ensureInitialized();
  p3.GenerationResultMapper.ensureInitialized();
  p3.GenerationEventMapper.ensureInitialized();
  p3.GenerationFinishedMapper.ensureInitialized();
  p3.ContentDeltaMapper.ensureInitialized();
  p3.TextDeltaMapper.ensureInitialized();
  p3.ReasoningDeltaMapper.ensureInitialized();
  p3.ToolArgumentsDeltaMapper.ensureInitialized();
  p3.GenerationStartedMapper.ensureInitialized();
  p3.PartStartedMapper.ensureInitialized();
  p3.PartDeltaMapper.ensureInitialized();
  p3.PartFinishedMapper.ensureInitialized();
  p3.UsageUpdatedMapper.ensureInitialized();
  p3.ProviderEventMapper.ensureInitialized();
  p3.FinishReasonMapper.ensureInitialized();
  p3.GenerationPartKindMapper.ensureInitialized();
  p4.MessageMapper.ensureInitialized();
  p4.UserMessageMapper.ensureInitialized();
  p4.AssistantMessageMapper.ensureInitialized();
  p4.InputPartMapper.ensureInitialized();
  p4.TextInputPartMapper.ensureInitialized();
  p4.OutputPartMapper.ensureInitialized();
  p4.TextOutputPartMapper.ensureInitialized();
  p4.ToolMessageMapper.ensureInitialized();
  p4.CitationMapper.ensureInitialized();
  p4.ProviderReplayMapper.ensureInitialized();
  p4.ReasoningOutputPartMapper.ensureInitialized();
  p4.RefusalOutputPartMapper.ensureInitialized();
  p4.OpaqueOutputPartMapper.ensureInitialized();
  p4.ToolCallPartMapper.ensureInitialized();
  p4.ProviderToolPartMapper.ensureInitialized();
  p4.ToolExecutionOwnerMapper.ensureInitialized();
  p4.ToolStatusMapper.ensureInitialized();
  p5.ModelCapabilitiesMapper.ensureInitialized();
  p5.CapabilitySupportMapper.ensureInitialized();
  p5.ModelCapabilityMapper.ensureInitialized();
  p6.ResponseMetadataMapper.ensureInitialized();
  p6.NativePayloadMapper.ensureInitialized();
  p6.NativeResponseMapper.ensureInitialized();
  p7.InvocationContextMapper.ensureInitialized();
  p7.ProviderObservationMapper.ensureInitialized();
  p7.ProviderObservationKindMapper.ensureInitialized();
  p7.ProviderOutcomeMapper.ensureInitialized();
  p8.ChatOptionsMapper.ensureInitialized();
  p8.NativeChatRequestMapper.ensureInitialized();
  p8.ChatResponseMapper.ensureInitialized();
  p8.ChatChoiceMapper.ensureInitialized();
  p9.ResponsesOptionsMapper.ensureInitialized();
  p9.ResponsesRequestMapper.ensureInitialized();
  p9.ResponsesResponseMapper.ensureInitialized();
  p10.SseEventMapper.ensureInitialized();
  p11.SettingMapper.ensureInitialized();
  p11.InheritSettingMapper.ensureInitialized();
  p11.ValueSettingMapper.ensureInitialized();
  p11.ClearSettingMapper.ensureInitialized();
  p11.NativeFieldMapper.ensureInitialized();
  p12.FunctionToolMapper.ensureInitialized();
  p12.ToolChoiceMapper.ensureInitialized();
  p12.AutoToolChoiceMapper.ensureInitialized();
  p12.NoToolChoiceMapper.ensureInitialized();
  p12.RequiredToolChoiceMapper.ensureInitialized();
  p12.NamedToolChoiceMapper.ensureInitialized();
  p12.OutputFormatMapper.ensureInitialized();
  p12.TextOutputMapper.ensureInitialized();
  p12.JsonObjectOutputMapper.ensureInitialized();
  p12.JsonSchemaOutputMapper.ensureInitialized();
  p12.ToolArgumentsMapper.ensureInitialized();
  p12.JsonToolArgumentsMapper.ensureInitialized();
  p12.FreeFormToolArgumentsMapper.ensureInitialized();
  p12.NativeToolArgumentsMapper.ensureInitialized();
  p12.MalformedToolArgumentsMapper.ensureInitialized();
  p12.ToolResultContentMapper.ensureInitialized();
  p12.JsonToolResultContentMapper.ensureInitialized();
  p12.TextToolResultContentMapper.ensureInitialized();
  p12.NativeToolResultContentMapper.ensureInitialized();
  p12.ToolResultMapper.ensureInitialized();
  p12.ToolSuccessMapper.ensureInitialized();
  p12.ToolFailureMapper.ensureInitialized();
}

