// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format off
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import 'src/embeddings/compatible_embedding_model.dart' as p0;
import 'src/embeddings/embeddings.dart' as p1;
import 'src/errors.dart' as p2;
import 'src/generation/generation.dart' as p3;
import 'src/messages/messages.dart' as p4;
import 'src/models.dart' as p5;
import 'src/native.dart' as p6;
import 'src/protocols/chat/chat_models.dart' as p7;
import 'src/protocols/responses/responses_models.dart' as p8;
import 'src/protocols/sse.dart' as p9;
import 'src/settings.dart' as p10;
import 'src/tools/tools.dart' as p11;

void initializeMappers() {
  p0.EmbeddingOptionsMapper.ensureInitialized();
  p1.EmbeddingInputMapper.ensureInitialized();
  p1.EmbeddingRequestMapper.ensureInitialized();
  p1.EmbeddingCapabilitiesMapper.ensureInitialized();
  p1.EmbeddingResultMapper.ensureInitialized();
  p1.IndexedEmbeddingMapper.ensureInitialized();
  p1.EmbeddingBatchMapper.ensureInitialized();
  p2.AiErrorMapper.ensureInitialized();
  p2.InvalidRequestErrorMapper.ensureInitialized();
  p2.UnsupportedFeatureErrorMapper.ensureInitialized();
  p2.ProviderErrorMapper.ensureInitialized();
  p2.TransportErrorMapper.ensureInitialized();
  p2.ProtocolErrorMapper.ensureInitialized();
  p2.ResponseLimitErrorMapper.ensureInitialized();
  p2.ClientClosedErrorMapper.ensureInitialized();
  p2.DeliveryStateMapper.ensureInitialized();
  p3.GenerationOptionsMapper.ensureInitialized();
  p3.ResolvedGenerationOptionsMapper.ensureInitialized();
  p3.GenerationRequestMapper.ensureInitialized();
  p3.UsageMapper.ensureInitialized();
  p3.GenerationResultMapper.ensureInitialized();
  p3.GenerationEventMapper.ensureInitialized();
  p3.GenerationFinishedMapper.ensureInitialized();
  p3.ContentDeltaMapper.ensureInitialized();
  p3.TextDeltaMapper.ensureInitialized();
  p3.ReasoningDeltaMapper.ensureInitialized();
  p3.ToolArgumentsDeltaMapper.ensureInitialized();
  p3.GenerationStartedMapper.ensureInitialized();
  p3.PartStartedMapper.ensureInitialized();
  p3.PartDeltaMapper.ensureInitialized();
  p3.PartFinishedMapper.ensureInitialized();
  p3.UsageUpdatedMapper.ensureInitialized();
  p3.ProviderEventMapper.ensureInitialized();
  p3.FinishReasonMapper.ensureInitialized();
  p3.GenerationPartKindMapper.ensureInitialized();
  p4.MessageMapper.ensureInitialized();
  p4.UserMessageMapper.ensureInitialized();
  p4.AssistantMessageMapper.ensureInitialized();
  p4.InputPartMapper.ensureInitialized();
  p4.TextInputPartMapper.ensureInitialized();
  p4.OutputPartMapper.ensureInitialized();
  p4.TextOutputPartMapper.ensureInitialized();
  p4.ToolMessageMapper.ensureInitialized();
  p4.CitationMapper.ensureInitialized();
  p4.ProviderReplayMapper.ensureInitialized();
  p4.ReasoningOutputPartMapper.ensureInitialized();
  p4.RefusalOutputPartMapper.ensureInitialized();
  p4.OpaqueOutputPartMapper.ensureInitialized();
  p4.ToolCallPartMapper.ensureInitialized();
  p4.ProviderToolPartMapper.ensureInitialized();
  p4.ToolExecutionOwnerMapper.ensureInitialized();
  p4.ToolStatusMapper.ensureInitialized();
  p5.ModelCapabilitiesMapper.ensureInitialized();
  p5.CapabilitySupportMapper.ensureInitialized();
  p5.ModelCapabilityMapper.ensureInitialized();
  p6.ResponseMetadataMapper.ensureInitialized();
  p6.NativePayloadMapper.ensureInitialized();
  p6.NativeResponseMapper.ensureInitialized();
  p7.ChatOptionsMapper.ensureInitialized();
  p7.NativeChatRequestMapper.ensureInitialized();
  p7.ChatResponseMapper.ensureInitialized();
  p7.ChatChoiceMapper.ensureInitialized();
  p8.ResponsesOptionsMapper.ensureInitialized();
  p8.ResponsesRequestMapper.ensureInitialized();
  p8.ResponsesResponseMapper.ensureInitialized();
  p9.SseEventMapper.ensureInitialized();
  p10.SettingMapper.ensureInitialized();
  p10.InheritSettingMapper.ensureInitialized();
  p10.ValueSettingMapper.ensureInitialized();
  p10.ClearSettingMapper.ensureInitialized();
  p10.NativeFieldMapper.ensureInitialized();
  p11.FunctionToolMapper.ensureInitialized();
  p11.ToolChoiceMapper.ensureInitialized();
  p11.AutoToolChoiceMapper.ensureInitialized();
  p11.NoToolChoiceMapper.ensureInitialized();
  p11.RequiredToolChoiceMapper.ensureInitialized();
  p11.NamedToolChoiceMapper.ensureInitialized();
  p11.OutputFormatMapper.ensureInitialized();
  p11.TextOutputMapper.ensureInitialized();
  p11.JsonObjectOutputMapper.ensureInitialized();
  p11.JsonSchemaOutputMapper.ensureInitialized();
  p11.ToolArgumentsMapper.ensureInitialized();
  p11.JsonToolArgumentsMapper.ensureInitialized();
  p11.FreeFormToolArgumentsMapper.ensureInitialized();
  p11.NativeToolArgumentsMapper.ensureInitialized();
  p11.MalformedToolArgumentsMapper.ensureInitialized();
  p11.ToolResultContentMapper.ensureInitialized();
  p11.JsonToolResultContentMapper.ensureInitialized();
  p11.TextToolResultContentMapper.ensureInitialized();
  p11.NativeToolResultContentMapper.ensureInitialized();
  p11.ToolResultMapper.ensureInitialized();
  p11.ToolSuccessMapper.ensureInitialized();
  p11.ToolFailureMapper.ensureInitialized();
}

