// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format off
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import 'src/embeddings/compatible_embedding_model.dart' as p0;
import 'src/embeddings/embeddings.dart' as p1;
import 'src/errors.dart' as p2;
import 'src/generation/generation.dart' as p3;
import 'src/messages/messages.dart' as p4;
import 'src/models.dart' as p5;
import 'src/native.dart' as p6;
import 'src/protocols/responses/responses_models.dart' as p7;
import 'src/protocols/sse.dart' as p8;
import 'src/settings.dart' as p9;
import 'src/tools/tools.dart' as p10;

void initializeMappers() {
  p0.EmbeddingOptionsMapper.ensureInitialized();
  p1.EmbeddingInputMapper.ensureInitialized();
  p1.EmbeddingRequestMapper.ensureInitialized();
  p1.EmbeddingCapabilitiesMapper.ensureInitialized();
  p1.EmbeddingResultMapper.ensureInitialized();
  p1.IndexedEmbeddingMapper.ensureInitialized();
  p1.EmbeddingBatchMapper.ensureInitialized();
  p2.AiErrorMapper.ensureInitialized();
  p2.InvalidRequestErrorMapper.ensureInitialized();
  p2.UnsupportedFeatureErrorMapper.ensureInitialized();
  p2.ProviderErrorMapper.ensureInitialized();
  p2.TransportErrorMapper.ensureInitialized();
  p2.ProtocolErrorMapper.ensureInitialized();
  p2.ResponseLimitErrorMapper.ensureInitialized();
  p2.ClientClosedErrorMapper.ensureInitialized();
  p2.DeliveryStateMapper.ensureInitialized();
  p3.GenerationOptionsMapper.ensureInitialized();
  p3.ResolvedGenerationOptionsMapper.ensureInitialized();
  p3.GenerationRequestMapper.ensureInitialized();
  p3.UsageMapper.ensureInitialized();
  p3.GenerationResultMapper.ensureInitialized();
  p3.GenerationEventMapper.ensureInitialized();
  p3.GenerationFinishedMapper.ensureInitialized();
  p3.ContentDeltaMapper.ensureInitialized();
  p3.TextDeltaMapper.ensureInitialized();
  p3.ReasoningDeltaMapper.ensureInitialized();
  p3.ToolArgumentsDeltaMapper.ensureInitialized();
  p3.GenerationStartedMapper.ensureInitialized();
  p3.PartStartedMapper.ensureInitialized();
  p3.PartDeltaMapper.ensureInitialized();
  p3.PartFinishedMapper.ensureInitialized();
  p3.UsageUpdatedMapper.ensureInitialized();
  p3.ProviderEventMapper.ensureInitialized();
  p3.FinishReasonMapper.ensureInitialized();
  p3.GenerationPartKindMapper.ensureInitialized();
  p4.MessageMapper.ensureInitialized();
  p4.UserMessageMapper.ensureInitialized();
  p4.AssistantMessageMapper.ensureInitialized();
  p4.InputPartMapper.ensureInitialized();
  p4.TextInputPartMapper.ensureInitialized();
  p4.OutputPartMapper.ensureInitialized();
  p4.TextOutputPartMapper.ensureInitialized();
  p4.ToolMessageMapper.ensureInitialized();
  p4.CitationMapper.ensureInitialized();
  p4.ProviderReplayMapper.ensureInitialized();
  p4.ReasoningOutputPartMapper.ensureInitialized();
  p4.RefusalOutputPartMapper.ensureInitialized();
  p4.OpaqueOutputPartMapper.ensureInitialized();
  p4.ToolCallPartMapper.ensureInitialized();
  p4.ProviderToolPartMapper.ensureInitialized();
  p4.ToolExecutionOwnerMapper.ensureInitialized();
  p4.ToolStatusMapper.ensureInitialized();
  p5.ModelCapabilitiesMapper.ensureInitialized();
  p5.CapabilitySupportMapper.ensureInitialized();
  p5.ModelCapabilityMapper.ensureInitialized();
  p6.ResponseMetadataMapper.ensureInitialized();
  p6.NativePayloadMapper.ensureInitialized();
  p6.NativeResponseMapper.ensureInitialized();
  p7.ResponsesOptionsMapper.ensureInitialized();
  p7.ResponsesRequestMapper.ensureInitialized();
  p7.ResponsesResponseMapper.ensureInitialized();
  p8.SseEventMapper.ensureInitialized();
  p9.SettingMapper.ensureInitialized();
  p9.InheritSettingMapper.ensureInitialized();
  p9.ValueSettingMapper.ensureInitialized();
  p9.ClearSettingMapper.ensureInitialized();
  p9.NativeFieldMapper.ensureInitialized();
  p10.FunctionToolMapper.ensureInitialized();
  p10.ToolChoiceMapper.ensureInitialized();
  p10.AutoToolChoiceMapper.ensureInitialized();
  p10.NoToolChoiceMapper.ensureInitialized();
  p10.RequiredToolChoiceMapper.ensureInitialized();
  p10.NamedToolChoiceMapper.ensureInitialized();
  p10.OutputFormatMapper.ensureInitialized();
  p10.TextOutputMapper.ensureInitialized();
  p10.JsonObjectOutputMapper.ensureInitialized();
  p10.JsonSchemaOutputMapper.ensureInitialized();
  p10.ToolArgumentsMapper.ensureInitialized();
  p10.JsonToolArgumentsMapper.ensureInitialized();
  p10.FreeFormToolArgumentsMapper.ensureInitialized();
  p10.NativeToolArgumentsMapper.ensureInitialized();
  p10.MalformedToolArgumentsMapper.ensureInitialized();
  p10.ToolResultContentMapper.ensureInitialized();
  p10.JsonToolResultContentMapper.ensureInitialized();
  p10.TextToolResultContentMapper.ensureInitialized();
  p10.NativeToolResultContentMapper.ensureInitialized();
  p10.ToolResultMapper.ensureInitialized();
  p10.ToolSuccessMapper.ensureInitialized();
  p10.ToolFailureMapper.ensureInitialized();
}

