builders:
  voxel:
    import: "package:voxel_generator/builder.dart"
    builder_factories: ["voxelBuilder"]
    build_extensions: {".dart": [".voxel.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before: ["voxel_generator:voxel_migration_bundle"]
  voxel_migration_bundle:
    import: "package:voxel_generator/builder.dart"
    builder_factories: ["voxelMigrationBundleBuilder"]
    build_extensions:
      "migrations/{{}}/journal.json": ["lib/{{}}.voxel_migrations.dart"]
    auto_apply: dependents
    build_to: source
    required_inputs: [".voxel.dart"]
