name: conflux
description: Pure functional values and effectful composition for Inframe.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  ack: ^1.2.0
  chrono_id:
    path: ../../chrono_id/chrono_id
  context:
    path: ../../context
  timezone: ^0.11.1

dev_dependencies:
  test: ^1.26.3
